In [ ]:
# DO NOT RUN THIS MORE THAN ONCE. This is a one-time data retrieval script to get historical minute data for TQQQ from Alpaca's free API. 

import pandas as pd
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame
from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.enums import DataFeed
from datetime import datetime
import os
from dotenv import load_dotenv

# 1. Setup your free Alpaca API Keys
load_dotenv()
API_KEY = os.environ.get("ALPACA_API_KEY")
SECRET_KEY = os.environ.get("ALPACA_SECRET_KEY")

# Initialize the historical data client
client = StockHistoricalDataClient(API_KEY, SECRET_KEY)

# 2. Define the parameters (Alpaca free tier goes back up to 7 years)
request_params = StockBarsRequest(
    symbol_or_symbols="TQQQ",
    timeframe=TimeFrame.Minute,
    start=datetime(2016, 1, 1), # Max out the free historical limit
    end=datetime(2025, 12, 31),
    # CRUCIAL FIX: Tells Alpaca to only return standard 9:30 AM - 4:00 PM data
    feed=DataFeed.SIP
)

print("Fetching historical minute data from Alpaca... This may take a moment.")
# 3. Retrieve the bars
bars = client.get_stock_bars(request_params)

# 4. Convert the results directly into a Pandas DataFrame
df = bars.df

# 5. Clean up multi-index format so it's a standard OHLCV table
df = df.reset_index()
df.set_index('timestamp', inplace=True)

# 6. Save it to a local CSV file right inside your VS Code workspace directory!
df.to_csv("TQQQ_intraday_data.csv")
print("Saved successfully to 'TQQQ_intraday_data.csv'!")

In [2]:
import pandas as pd
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame
from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.enums import DataFeed
from datetime import datetime
import os
from dotenv import load_dotenv

In [4]:
# 1. Load your raw file
df = pd.read_csv("TQQQ_intraday_data.csv", parse_dates=['timestamp'], index_col='timestamp')

# 2. Rename columns to match what Backtesting.py expects (Open, High, Low, Close, Volume)
df = df.rename(columns={
    'open': 'Open',
    'high': 'High',
    'low': 'Low',
    'close': 'Close',
    'volume': 'Volume'
})

# 3. Convert UTC (+00:00) directly into New York Time (Eastern Time)
df.index = df.index.tz_convert('America/New_York')

# 4. Strip the timezone text ('-05:00' or '-04:00') so it behaves like standard local time
df.index = df.index.tz_localize(None)

# 5. Filter strictly for US Stock Market Core Hours (09:30 AM to 04:00 PM)
# This throws away any overnight/pre-market noise
df = df.between_time('09:30', '16:00')

# 6. Check your new structure
print(f"Total rows remaining: {len(df)}")
df

Total rows remaining: 779263

,symbol,Open,High,Low,Close,Volume,trade_count,vwap
timestamp,,,,,,,,
2016-01-04 09:30:00,TQQQ,106.65,106.7300,106.0000,106.0800,262807.0,606.0,106.578812
2016-01-04 09:31:00,TQQQ,106.08,106.0830,105.5600,105.8750,35666.0,246.0,105.827157
2016-01-04 09:32:00,TQQQ,105.89,106.3599,105.8301,106.2950,33076.0,155.0,106.162660
2016-01-04 09:33:00,TQQQ,106.27,106.2700,105.8795,106.1352,33882.0,218.0,106.046604
2016-01-04 09:34:00,TQQQ,106.11,106.1100,105.6700,105.8304,22509.0,174.0,105.850556
...,...,...,...,...,...,...,...,...
2023-12-29 15:56:00,TQQQ,50.58,50.6899,50.5800,50.6399,220591.0,757.0,50.629077
2023-12-29 15:57:00,TQQQ,50.63,50.6450,50.5700,50.5766,348458.0,906.0,50.606164
2023-12-29 15:58:00,TQQQ,50.58,50.6400,50.5800,50.6001,260496.0,754.0,50.610019
2023-12-29 15:59:00,TQQQ,50.60,50.8250,50.5900,50.7100,1095780.0,2466.0,50.690153
2023-12-29 16:00:00,TQQQ,50.70,50.7300,50.6100,50.6298,216047.0,145.0,50.686283

In [ ]:
# Final (Original)

import pandas as pd
import datetime as dt
from backtesting import Backtest, Strategy


EARLY_CLOSE_DATES = [
    '2017-07-03 12:59:00',
    '2018-07-03 12:59:00',
    '2018-11-23 12:59:00',
    '2019-12-24 12:59:00',
    '2020-11-27 12:59:00',
    '2020-12-24 12:59:00'
]

# 2. create a strategy class
class OpeningRangeBreakout(Strategy):
    open_range_minutes = 5 # length of the opening range
    last_minute_bar_in_opening_range = dt.time(9, 30 + open_range_minutes)
    exit_minute_bar = dt.time(15, 59)
    risk_percent = 0.01
    take_profit_multiple = 10
    max_leverage = 4

    # what do we want to initialize at the beginning
    def init(self):
        self.current_day        = None   # tracks the current day (YYYY-MM-DD)
        self.current_day_open   = None
        self.opening_range_high = None   # opening range high
        self.opening_range_low  = None   # opening range low

    # wait every day is going to have a different opening range high and low
    def _reset_range(self, day, open):
        self.current_day        = day
        self.current_day_open   = open
        self.opening_range_high = None
        self.opening_range_low  = None


    def _get_position_size(self, entry_price: float, stop_price: float) -> int:
        per_share_risk = abs(entry_price - stop_price)  #  |P − S|  =  R

        if per_share_risk == 0:
            return 0

        # Risk-based cap: position that loses 1 % of equity at the stop
        shares_by_risk = (self.risk_percent * self.equity) / per_share_risk

        # Leverage-based cap: shares affordable with 4× buying power
        shares_by_leverage = (self.max_leverage * self.equity) / entry_price

        # Final size: smaller of the two, floored to an int
        return int(min(shares_by_risk, shares_by_leverage))

    def next(self):
        # get the timestamp and extract the date
        t = self.data.index[-1]
        current_bar_date = t.date()

        # detect when the date changes to a new day
        if current_bar_date != self.current_day:
            self._reset_range(current_bar_date, self.data.Open[-1])
            print(f"new date {current_bar_date}")

        # calculate opening range
        if t.time() <= self.last_minute_bar_in_opening_range:
            if self.opening_range_high is not None:
                self.opening_range_high = max(self.opening_range_high, self.data.High[-1])
            else:
                self.opening_range_high = self.data.High[-1]

            if self.opening_range_low is not None:
                self.opening_range_low = min(self.opening_range_low, self.data.Low[-1])
            else:
                self.opening_range_low = self.data.Low[-1]

            if t.time() < self.last_minute_bar_in_opening_range:
                return  # don’t trade yet

        # Right when the opening range closes, log the opening range high and low for debugging
        if t.time() == self.last_minute_bar_in_opening_range:
          print(f"opening range high is {self.opening_range_high}")
          print(f"opening range low is {self.opening_range_low}")

          if not self.position:
            range_size = self.opening_range_high - self.opening_range_low
            planned_entry_price = self.data.Close[-1]

            if self.data.Close[-1] > self.current_day_open:
                stop_loss_price = self.opening_range_low
                position_size = self._get_position_size(planned_entry_price, stop_loss_price)
                take_profit_price = planned_entry_price + (self.take_profit_multiple * range_size)

                print(f"going long, position size {position_size} at planned price {planned_entry_price}, stop loss {stop_loss_price}")
                order = self.buy(size=position_size, tp=take_profit_price, sl=stop_loss_price)

            elif self.data.Close[-1] < self.current_day_open:
                stop_loss_price = self.opening_range_high
                position_size = self._get_position_size(planned_entry_price, stop_loss_price)
                take_profit_price = planned_entry_price - (self.take_profit_multiple * range_size)

                print(f"going short, position size {position_size} shares at planned price {planned_entry_price}, stop loss {stop_loss_price}")
                order = self.sell(size=position_size, tp=take_profit_price, sl=stop_loss_price)
            else:
              print("doji, doing nothing")


        current_bar_date_time = f"{current_bar_date} {t.time()}"

        # is market is about to close, close my position
        if self.position and t.time() == self.exit_minute_bar or current_bar_date_time in EARLY_CLOSE_DATES:
          print("closing out position")
          self.position.close()



# 1. read a csv of minute data
df = pd.read_csv("TQQQ_intraday_data.csv", parse_dates=['timestamp'], index_col='timestamp')
df = df.rename(columns={
    'open': 'Open',
    'high': 'High',
    'low': 'Low',
    'close': 'Close',
    'volume': 'Volume'
})
df.index = df.index.tz_convert('America/New_York')
df.index = df.index.tz_localize(None)
df = df.between_time('09:30', '16:00')
#df = df.loc['2016-01-05':'2023-12-29']
# df

def per_share_commission(size, price):
    return abs(size) * 0.0005

# 3. create a backtest, pass in data and the strategy you want to run on the data
bt = Backtest(df, OpeningRangeBreakout, cash=25_000, commission=per_share_commission, margin=0.25)

# run the strategy
stats = bt.run()

# plot ths strategy
bt.plot()

print(stats)

new date 2016-01-04
opening range high is 106.3599
opening range low is 105.56
going short, position size 694 shares at planned price 106.0, stop loss 106.3599
new date 2016-01-05
opening range high is 108.93
opening range low is 107.77
going short, position size 222 shares at planned price 107.8201, stop loss 108.93
closing out position
new date 2016-01-06
opening range high is 101.83
opening range low is 100.84
going long, position size 584 at planned price 101.27, stop loss 100.84
closing out position
new date 2016-01-07
opening range high is 96.86
opening range low is 96.05
going long, position size 344 at planned price 96.816, stop loss 96.05
new date 2016-01-08
opening range high is 96.96
opening range low is 95.38
going long, position size 224 at planned price 96.54, stop loss 95.38
new date 2016-01-11
opening range high is 94.03
opening range low is 93.13
going short, position size 297 shares at planned price 93.16, stop loss 94.03
closing out position
new date 2016-01-12
opening range high is 95.8299
opening range low is 94.5
going long, position size 250 at planned price 95.5405, stop loss 94.5
new date 2016-01-13
opening range high is 96.87
opening range low is 96.15
going long, position size 487 at planned price 96.68, stop loss 96.15
new date 2016-01-14
opening range high is 86.743
opening range low is 85.86
going short, position size 307 shares at planned price 85.9109, stop loss 86.743
new date 2016-01-15
opening range high is 83.64
opening range low is 81.396
going long, position size 116 at planned price 83.5801, stop loss 81.396
new date 2016-01-19
opening range high is 86.124
opening range low is 84.91
going short, position size 242 shares at planned price 85.09, stop loss 86.124
closing out position
new date 2016-01-20
opening range high is 79.938
opening range low is 78.73
going long, position size 351 at planned price 79.46, stop loss 78.73
new date 2016-01-21
opening range high is 83.2
opening range low is 81.27
going short, position size 429 shares at planned price 82.61, stop loss 83.2
new date 2016-01-22
opening range high is 87.53
opening range low is 86.9133
going short, position size 449 shares at planned price 86.9716, stop loss 87.53
new date 2016-01-25
opening range high is 89.02
opening range low is 88.41
going short, position size 487 shares at planned price 88.51, stop loss 89.02
new date 2016-01-26
opening range high is 87.0
opening range low is 85.954
doji, doing nothing
new date 2016-01-27
opening range high is 86.91
opening range low is 86.13
going long, position size 326 at planned price 86.884, stop loss 86.13
new date 2016-01-28
opening range high is 85.4
opening range low is 84.7
going short, position size 420 shares at planned price 84.82, stop loss 85.4
closing out position
new date 2016-01-29
opening range high is 85.5
opening range low is 84.5501
going long, position size 314 at planned price 85.33, stop loss 84.5501
closing out position
new date 2016-02-01
opening range high is 88.79
opening range low is 88.07
going short, position size 361 shares at planned price 88.07, stop loss 88.79
new date 2016-02-02
opening range high is 89.57
opening range low is 88.88
going short, position size 390 shares at planned price 88.91, stop loss 89.57
closing out position
new date 2016-02-03
opening range high is 86.47
opening range low is 85.5888
going short, position size 309 shares at planned price 85.5888, stop loss 86.47
closing out position
new date 2016-02-04
opening range high is 83.5607
opening range low is 82.54
going long, position size 821 at planned price 82.88, stop loss 82.54
new date 2016-02-05
opening range high is 82.781
opening range low is 81.21
going short, position size 228 shares at planned price 81.5699, stop loss 82.781
closing out position
new date 2016-02-08
opening range high is 70.8599
opening range low is 69.82
going short, position size 280 shares at planned price 69.8201, stop loss 70.8599
new date 2016-02-09
opening range high is 69.43
opening range low is 68.22
going long, position size 251 at planned price 69.37, stop loss 68.22
closing out position
new date 2016-02-10
opening range high is 73.55
opening range low is 72.35
going short, position size 269 shares at planned price 72.466, stop loss 73.55
new date 2016-02-11
opening range high is 69.81
opening range low is 68.64
going long, position size 278 at planned price 69.68, stop loss 68.64
new date 2016-02-12
opening range high is 73.935
opening range low is 72.85
going short, position size 681 shares at planned price 73.515, stop loss 73.935
new date 2016-02-16
opening range high is 78.21
opening range low is 77.62
going long, position size 602 at planned price 78.09, stop loss 77.62
new date 2016-02-17
opening range high is 81.82
opening range low is 81.16
going long, position size 572 at planned price 81.65, stop loss 81.16
new date 2016-02-18
opening range high is 85.73
opening range low is 84.28
going short, position size 198 shares at planned price 84.33, stop loss 85.73
closing out position
new date 2016-02-19
opening range high is 81.66
opening range low is 80.91
going long, position size 975 at planned price 81.2, stop loss 80.91
new date 2016-02-22
opening range high is 85.6
opening range low is 84.78
going long, position size 356 at planned price 85.566, stop loss 84.78
closing out position
new date 2016-02-23
opening range high is 85.64
opening range low is 85.0
going long, position size 489 at planned price 85.58, stop loss 85.0
new date 2016-02-24
opening range high is 79.8
opening range low is 79.0
going short, position size 611 shares at planned price 79.3401, stop loss 79.8
new date 2016-02-25
opening range high is 85.81
opening range low is 85.2844
going long, position size 1049 at planned price 85.55, stop loss 85.2844
new date 2016-02-26
opening range high is 89.21
opening range low is 88.59
going long, position size 466 at planned price 89.18, stop loss 88.59
new date 2016-02-29
opening range high is 87.2389
opening range low is 86.37
going long, position size 313 at planned price 87.2389, stop loss 86.37
new date 2016-03-01
opening range high is 87.34
opening range low is 86.598
going short, position size 508 shares at planned price 86.81, stop loss 87.34
new date 2016-03-02
opening range high is 92.72
opening range low is 92.18
going long, position size 523 at planned price 92.69, stop loss 92.18
new date 2016-03-03
opening range high is 92.61
opening range low is 91.98
going short, position size 1143 shares at planned price 92.47, stop loss 92.61
new date 2016-03-04
opening range high is 92.86
opening range low is 91.27
going short, position size 164 shares at planned price 91.27, stop loss 92.86
new date 2016-03-07
opening range high is 91.18
opening range low is 90.65
going long, position size 490 at planned price 91.18, stop loss 90.65
new date 2016-03-08
opening range high is 88.92
opening range low is 88.28
going short, position size 547 shares at planned price 88.45, stop loss 88.92
new date 2016-03-09
opening range high is 89.61
opening range low is 88.58
going short, position size 263 shares at planned price 88.64, stop loss 89.61
new date 2016-03-10
opening range high is 91.8
opening range low is 90.6101
going short, position size 592 shares at planned price 91.3735, stop loss 91.8
new date 2016-03-11
opening range high is 92.98
opening range low is 92.07
going short, position size 531 shares at planned price 92.51, stop loss 92.98
new date 2016-03-14
opening range high is 93.74
opening range low is 93.31
going long, position size 879 at planned price 93.591, stop loss 93.31
closing out position
new date 2016-03-15
opening range high is 94.3399
opening range low is 93.5
going short, position size 307 shares at planned price 93.5, stop loss 94.3399
new date 2016-03-16
opening range high is 94.55
opening range low is 94.02
going long, position size 492 at planned price 94.54, stop loss 94.02
closing out position
new date 2016-03-17
opening range high is 97.166
opening range low is 96.2445
going long, position size 318 at planned price 97.09, stop loss 96.2445
new date 2016-03-18
opening range high is 98.17
opening range low is 97.5601
going short, position size 580 shares at planned price 97.71, stop loss 98.17
new date 2016-03-21
opening range high is 97.75
opening range low is 97.08
going long, position size 412 at planned price 97.72, stop loss 97.08
new date 2016-03-22
opening range high is 97.67
opening range low is 97.03
going long, position size 507 at planned price 97.5463, stop loss 97.03
closing out position
new date 2016-03-23
opening range high is 99.1796
opening range low is 98.57
going long, position size 446 at planned price 99.1796, stop loss 98.57
new date 2016-03-24
opening range high is 95.88
opening range low is 95.3
going long, position size 549 at planned price 95.79, stop loss 95.3
closing out position
new date 2016-03-28
opening range high is 98.2
opening range low is 97.18
going short, position size 279 shares at planned price 97.2093, stop loss 98.2
closing out position
new date 2016-03-29
opening range high is 96.475
opening range low is 96.121
going short, position size 975 shares at planned price 96.19, stop loss 96.475
new date 2016-03-30
opening range high is 103.48
opening range low is 102.9501
going long, position size 571 at planned price 103.43, stop loss 102.9501
new date 2016-03-31
opening range high is 103.12
opening range low is 102.6796
going short, position size 631 shares at planned price 102.69, stop loss 103.12
new date 2016-04-01
opening range high is 100.9199
opening range low is 100.27
going short, position size 495 shares at planned price 100.3772, stop loss 100.9199
new date 2016-04-04
opening range high is 105.7
opening range low is 105.3242
going short, position size 833 shares at planned price 105.38, stop loss 105.7
new date 2016-04-05
opening range high is 102.54
opening range low is 102.09
going long, position size 800 at planned price 102.42, stop loss 102.09
new date 2016-04-06
opening range high is 102.61
opening range low is 101.9
going long, position size 443 at planned price 102.49, stop loss 101.9
closing out position
new date 2016-04-07
opening range high is 105.03
opening range low is 104.45
going long, position size 527 at planned price 104.98, stop loss 104.45
new date 2016-04-08
opening range high is 103.94
opening range low is 103.4201
going short, position size 659 shares at planned price 103.52, stop loss 103.94
new date 2016-04-11
opening range high is 103.55
opening range low is 102.66
going long, position size 637 at planned price 103.09, stop loss 102.66
new date 2016-04-12
opening range high is 101.14
opening range low is 100.19
going short, position size 388 shares at planned price 100.441, stop loss 101.14
new date 2016-04-13
opening range high is 105.7271
opening range low is 105.07
going long, position size 409 at planned price 105.7271, stop loss 105.07
closing out position
new date 2016-04-14
opening range high is 107.2899
opening range low is 106.67
going short, position size 527 shares at planned price 106.77, stop loss 107.2899
new date 2016-04-15
opening range high is 107.15
opening range low is 106.7
going short, position size 602 shares at planned price 106.7, stop loss 107.15
new date 2016-04-18
opening range high is 105.64
opening range low is 105.16
going long, position size 570 at planned price 105.63, stop loss 105.16
closing out position
new date 2016-04-19
opening range high is 109.0
opening range low is 107.56
going short, position size 216 shares at planned price 107.7, stop loss 109.0
closing out position
new date 2016-04-20
opening range high is 106.2
opening range low is 105.46
going short, position size 460 shares at planned price 105.5808, stop loss 106.2
new date 2016-04-21
opening range high is 106.214
opening range low is 105.73
going short, position size 764 shares at planned price 105.845, stop loss 106.214
new date 2016-04-22
opening range high is 103.26
opening range low is 101.79
going long, position size 202 at planned price 103.17, stop loss 101.79
new date 2016-04-25
opening range high is 101.08
opening range low is 100.33
going long, position size 418 at planned price 100.99, stop loss 100.33
new date 2016-04-26
opening range high is 101.99
opening range low is 101.3901
going short, position size 557 shares at planned price 101.5, stop loss 101.99
new date 2016-04-27
opening range high is 98.0
opening range low is 96.77
going long, position size 242 at planned price 97.8841, stop loss 96.77
new date 2016-04-28
opening range high is 98.0
opening range low is 97.48
going short, position size 991 shares at planned price 97.7301, stop loss 98.0
new date 2016-04-29
opening range high is 94.3044
opening range low is 93.49
going long, position size 627 at planned price 93.91, stop loss 93.49
new date 2016-05-02
opening range high is 93.21
opening range low is 92.24
going short, position size 303 shares at planned price 92.35, stop loss 93.21
new date 2016-05-03
opening range high is 93.55
opening range low is 92.9
going long, position size 496 at planned price 93.42, stop loss 92.9
new date 2016-05-04
opening range high is 91.3228
opening range low is 90.75
going long, position size 625 at planned price 91.16, stop loss 90.75
new date 2016-05-05
opening range high is 91.82
opening range low is 91.31
going short, position size 543 shares at planned price 91.352, stop loss 91.82
new date 2016-05-06
opening range high is 89.95
opening range low is 89.2
going long, position size 360 at planned price 89.9003, stop loss 89.2
new date 2016-05-09
opening range high is 92.881
opening range low is 91.92
going long, position size 259 at planned price 92.881, stop loss 91.92
closing out position
new date 2016-05-10
opening range high is 93.99
opening range low is 93.63
going long, position size 923 at planned price 93.9, stop loss 93.63
new date 2016-05-11
opening range high is 96.27
opening range low is 96.0
going long, position size 1027 at planned price 96.1199, stop loss 96.0
new date 2016-05-12
opening range high is 94.93
opening range low is 94.44
doji, doing nothing
new date 2016-05-13
opening range high is 93.25
opening range low is 92.41
going long, position size 399 at planned price 93.0266, stop loss 92.41
new date 2016-05-16
opening range high is 92.52
opening range low is 91.85
going long, position size 364 at planned price 92.52, stop loss 91.85
closing out position
new date 2016-05-17
opening range high is 95.67
opening range low is 94.8452
going long, position size 626 at planned price 95.25, stop loss 94.8452
new date 2016-05-18
opening range high is 91.58
opening range low is 90.95
going long, position size 678 at planned price 91.32, stop loss 90.95
new date 2016-05-19
opening range high is 91.84
opening range low is 91.1608
going long, position size 469 at planned price 91.69, stop loss 91.1608
new date 2016-05-20
opening range high is 92.9
opening range low is 91.99
going long, position size 273 at planned price 92.89, stop loss 91.99
closing out position
new date 2016-05-23
opening range high is 94.9
opening range low is 94.06
going long, position size 304 at planned price 94.88, stop loss 94.06
new date 2016-05-24
opening range high is 95.86
opening range low is 95.16
going long, position size 354 at planned price 95.8564, stop loss 95.16
closing out position
new date 2016-05-25
opening range high is 100.7364
opening range low is 100.31
going short, position size 866 shares at planned price 100.437, stop loss 100.7364
new date 2016-05-26
opening range high is 102.18
opening range low is 101.49
going short, position size 413 shares at planned price 101.56, stop loss 102.18
new date 2016-05-27
opening range high is 102.91
opening range low is 102.5
going long, position size 635 at planned price 102.9, stop loss 102.5
closing out position
new date 2016-05-31
opening range high is 104.46
opening range low is 104.063
going short, position size 999 shares at planned price 104.41, stop loss 104.46
new date 2016-06-01
opening range high is 103.84
opening range low is 103.44
going short, position size 704 shares at planned price 103.47, stop loss 103.84
new date 2016-06-02
opening range high is 103.994
opening range low is 103.48
going short, position size 779 shares at planned price 103.6637, stop loss 103.994
new date 2016-06-03
opening range high is 104.721
opening range low is 103.97
going short, position size 356 shares at planned price 104.004, stop loss 104.721
closing out position
new date 2016-06-06
opening range high is 104.21
opening range low is 103.89
going short, position size 886 shares at planned price 103.92, stop loss 104.21
new date 2016-06-07
opening range high is 105.14
opening range low is 104.7
going short, position size 937 shares at planned price 104.8685, stop loss 105.14
new date 2016-06-08
opening range high is 104.63
opening range low is 104.44
going short, position size 963 shares at planned price 104.53, stop loss 104.63
new date 2016-06-09
opening range high is 103.51
opening range low is 103.14
going short, position size 969 shares at planned price 103.2694, stop loss 103.51
new date 2016-06-10
opening range high is 101.53
opening range low is 101.0801
going long, position size 825 at planned price 101.38, stop loss 101.0801
new date 2016-06-13
opening range high is 99.41
opening range low is 98.75
going long, position size 490 at planned price 99.25, stop loss 98.75
new date 2016-06-14
opening range high is 98.36
opening range low is 97.18
going long, position size 212 at planned price 98.3235, stop loss 97.18
new date 2016-06-15
opening range high is 98.749
opening range low is 98.2028
going short, position size 481 shares at planned price 98.25, stop loss 98.749
new date 2016-06-16
opening range high is 95.87
opening range low is 95.37
going short, position size 529 shares at planned price 95.42, stop loss 95.87
new date 2016-06-17
opening range high is 97.45
opening range low is 95.9701
going short, position size 168 shares at planned price 96.05, stop loss 97.45
closing out position
new date 2016-06-20
opening range high is 98.3
opening range low is 97.81
going long, position size 792 at planned price 98.11, stop loss 97.81
new date 2016-06-21
opening range high is 97.13
opening range low is 96.52
going long, position size 470 at planned price 97.02, stop loss 96.52
new date 2016-06-22
opening range high is 97.47
opening range low is 97.15
going short, position size 831 shares at planned price 97.19, stop loss 97.47
new date 2016-06-23
opening range high is 98.798
opening range low is 98.2
going short, position size 482 shares at planned price 98.32, stop loss 98.798
new date 2016-06-24
opening range high is 91.0
opening range low is 89.1
going long, position size 134 at planned price 90.7949, stop loss 89.1
new date 2016-06-27
opening range high is 86.39
opening range low is 85.5625
going short, position size 341 shares at planned price 85.73, stop loss 86.39
closing out position
new date 2016-06-28
opening range high is 86.05
opening range low is 85.59
going long, position size 1018 at planned price 85.8199, stop loss 85.59
closing out position
new date 2016-06-29
opening range high is 91.0348
opening range low is 90.34
going long, position size 542 at planned price 90.82, stop loss 90.34
closing out position
new date 2016-06-30
opening range high is 93.95
opening range low is 93.25
going long, position size 477 at planned price 93.82, stop loss 93.25
new date 2016-07-01
opening range high is 97.0
opening range low is 96.04
going long, position size 281 at planned price 97.0, stop loss 96.04
closing out position
new date 2016-07-05
opening range high is 96.56
opening range low is 95.95
going short, position size 476 shares at planned price 95.99, stop loss 96.56
closing out position
new date 2016-07-06
opening range high is 94.98
opening range low is 93.896
going short, position size 261 shares at planned price 93.94, stop loss 94.98
new date 2016-07-07
opening range high is 99.14
opening range low is 98.53

/Users/jonathanneo/LearnQuant/.venv/lib/python3.13/site-packages/backtesting/_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

Start                     2016-01-04 09:30:00
End                       2023-12-29 16:00:00
Duration                   2916 days 06:30:00
Exposure Time [%]                     35.6329
Equity Final [$]                  134687.3969
Equity Peak [$]                   150213.5344
Commissions [$]                      3411.287
Return [%]                          438.74959
Buy & Hold Return [%]               -52.27206
Return (Ann.) [%]                    23.63824
Volatility (Ann.) [%]                 47.3405
CAGR [%]                             15.66459
Sharpe Ratio                          0.49932
Sortino Ratio                         1.77715
Calmar Ratio                           0.6006
Alpha [%]                           437.97469
Beta                                 -0.01482
Max. Drawdown [%]                   -39.35765
Avg. Drawdown [%]                    -1.18428
Max. Drawdown Duration      629 days 00:11:00
Avg. Drawdown Duration        4 days 07:14:00
# Trades                                 1970
Win Rate [%]                         25.58376
Best Trade [%]                       18.10599
Worst Trade [%]                      -5.54025
Avg. Trade [%]                        0.06067
Max. Trade Duration           3 days 06:24:00
Avg. Trade Duration           0 days 02:23:00
Profit Factor                         1.13235
Expectancy [%]                        0.07955
SQN                                   1.55627
Kelly Criterion                       0.02777
_strategy                 OpeningRangeBrea...
_equity_curve                             ...
_trades                          Size  Ent...
dtype: object

In [ ]:
# Modified to align to the logic in the research paper as much as possible

import pandas as pd
import datetime as dt
from backtesting import Backtest, Strategy


EARLY_CLOSE_DATES = [
    '2017-07-03 12:59:00',
    '2018-07-03 12:59:00',
    '2018-11-23 12:59:00',
    '2019-12-24 12:59:00',
    '2020-11-27 12:59:00',
    '2020-12-24 12:59:00'
]

# 2. create a strategy class
class OpeningRangeBreakout(Strategy):
    open_range_minutes = 5 # length of the opening range
    last_minute_bar_in_opening_range = dt.time(9, 30 + open_range_minutes)
    exit_minute_bar = dt.time(15, 59)
    risk_percent = 0.01
    take_profit_multiple = 3
    max_leverage = 4

    # what do we want to initialize at the beginning
    def init(self):
        self.current_day        = None   # tracks the current day (YYYY-MM-DD)
        self.current_day_open   = None
        self.opening_range_high = None   # opening range high
        self.opening_range_low  = None   # opening range low
        self.traded_today = False 

    # wait every day is going to have a different opening range high and low
    def _reset_range(self, day, open):
        self.current_day        = day
        self.current_day_open   = open
        self.opening_range_high = None
        self.opening_range_low  = None
        self.traded_today = False


    def _get_position_size(self, entry_price: float, stop_price: float) -> int:
        per_share_risk = abs(entry_price - stop_price)  #  |P − S|  =  R

        if per_share_risk == 0:
            return 0

        # Risk-based cap: position that loses 1 % of equity at the stop
        shares_by_risk = (self.risk_percent * self.equity) / per_share_risk

        # Leverage-based cap: shares affordable with 4× buying power
        shares_by_leverage = (self.max_leverage * self.equity) / entry_price

        # Final size: smaller of the two, floored to an int
        return int(min(shares_by_risk, shares_by_leverage))

    def next(self):
            t = self.data.index[-1]
            current_bar_date = t.date()

            # 1. Handle New Day Reset
            if current_bar_date != self.current_day:
                self._reset_range(current_bar_date, self.data.Open[-1])
                print(f"new date {current_bar_date}")

            # 2. Build the Opening Range (09:30 to 09:35)
            if t.time() <= self.last_minute_bar_in_opening_range:
                if self.opening_range_high is not None:
                    self.opening_range_high = max(self.opening_range_high, self.data.High[-1])
                else:
                    self.opening_range_high = self.data.High[-1]

                if self.opening_range_low is not None:
                    self.opening_range_low = min(self.opening_range_low, self.data.Low[-1])
                else:
                    self.opening_range_low = self.data.Low[-1]

                return  # CRUCIAL: Do not evaluate trades during the opening range window

            # 3. TRUE BREAKOUT MONITORING (09:36 AM onwards)
            if not self.position and not self.traded_today:
                range_size = self.opening_range_high - self.opening_range_low
                current_close = self.data.Close[-1]

                # True Long Breakout Condition: Close crosses ABOVE 5-minute High
                if current_close > self.opening_range_high:
                    stop_loss_price = self.opening_range_low
                    take_profit_price = current_close + (self.take_profit_multiple * range_size)

                    # SAFETY CHECK: Only place order if TP is safely above current price
                    if take_profit_price > current_close:
                        position_size = self._get_position_size(current_close, stop_loss_price)
                        print(f"TRUE LONG BREAKOUT! Close ({current_close}) > High ({self.opening_range_high})")
                        self.buy(size=position_size, tp=take_profit_price, sl=stop_loss_price)
                        self.traded_today = True
                    else:
                        print("Long breakout skipped: Take profit price too close to entry.")

                # True Short Breakout Condition: Close crosses BELOW 5-minute Low
                elif current_close < self.opening_range_low:
                    stop_loss_price = self.opening_range_high
                    take_profit_price = current_close - (self.take_profit_multiple * range_size)

                    # SAFETY CHECK: Only place order if TP is safely BELOW current price
                    if take_profit_price < current_close:
                        position_size = self._get_position_size(current_close, stop_loss_price)
                        print(f"TRUE SHORT BREAKOUT! Close ({current_close}) < Low ({self.opening_range_low})")
                        self.sell(size=position_size, tp=take_profit_price, sl=stop_loss_price)
                        self.traded_today = True
                    else:
                        print("Short breakout skipped: Take profit price too close to entry.")

            # 4. End of Day Closeout
            current_bar_date_time = f"{current_bar_date} {t.time()}"
            if self.position and (t.time() == self.exit_minute_bar or current_bar_date_time in EARLY_CLOSE_DATES):
                print("closing out position at end of day")
                self.position.close()
                self.traded_today = False  # reset for the next day

# 1. read a csv of minute data
df = pd.read_csv("TQQQ_intraday_data.csv", parse_dates=['timestamp'], index_col='timestamp')
df = df.rename(columns={
    'open': 'Open',
    'high': 'High',
    'low': 'Low',
    'close': 'Close',
    'volume': 'Volume'
})
df.index = df.index.tz_convert('America/New_York')
df.index = df.index.tz_localize(None)
df = df.between_time('09:30', '16:00')

def per_share_commission(size, price):
    return abs(size) * 0.0005

# 3. create a backtest, pass in data and the strategy you want to run on the data
bt = Backtest(df, OpeningRangeBreakout, cash=25_000, commission=per_share_commission, margin=0.25)

# run the strategy
stats = bt.run()

# plot ths strategy
bt.plot()

print(stats)

new date 2016-01-04
TRUE LONG BREAKOUT! Close (106.51) > High (106.3599)
new date 2016-01-05
TRUE SHORT BREAKOUT! Close (107.64) < Low (107.77)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (106.5) < Low (107.77)
new date 2016-01-06
TRUE LONG BREAKOUT! Close (101.9772) > High (101.83)
new date 2016-01-07
TRUE LONG BREAKOUT! Close (97.1899) > High (96.86)
new date 2016-01-08
TRUE LONG BREAKOUT! Close (97.145) > High (96.96)
new date 2016-01-11
TRUE SHORT BREAKOUT! Close (92.9) < Low (93.13)
new date 2016-01-12
TRUE LONG BREAKOUT! Close (96.1472) > High (95.8299)
new date 2016-01-13
TRUE LONG BREAKOUT! Close (97.12) > High (96.87)
new date 2016-01-14
TRUE SHORT BREAKOUT! Close (85.71) < Low (85.86)
new date 2016-01-15
TRUE LONG BREAKOUT! Close (83.67) > High (83.64)
new date 2016-01-19
TRUE SHORT BREAKOUT! Close (84.9) < Low (84.91)
new date 2016-01-20
TRUE SHORT BREAKOUT! Close (78.22) < Low (78.73)
new date 2016-01-21
TRUE SHORT BREAKOUT! Close (81.221) < Low (81.27)
new date 2016-01-22
TRUE SHORT BREAKOUT! Close (86.73) < Low (86.9133)
new date 2016-01-25
TRUE SHORT BREAKOUT! Close (88.37) < Low (88.41)
new date 2016-01-26
TRUE SHORT BREAKOUT! Close (85.85) < Low (85.954)
new date 2016-01-27
TRUE SHORT BREAKOUT! Close (86.1211) < Low (86.13)
new date 2016-01-28
TRUE SHORT BREAKOUT! Close (84.56) < Low (84.7)
new date 2016-01-29
TRUE LONG BREAKOUT! Close (85.96) > High (85.5)
new date 2016-02-01
TRUE LONG BREAKOUT! Close (89.2605) > High (88.79)
new date 2016-02-02
TRUE SHORT BREAKOUT! Close (88.74) < Low (88.88)
new date 2016-02-03
TRUE SHORT BREAKOUT! Close (85.5124) < Low (85.5888)
new date 2016-02-04
TRUE SHORT BREAKOUT! Close (82.2047) < Low (82.54)
new date 2016-02-05
TRUE SHORT BREAKOUT! Close (81.2099) < Low (81.21)
new date 2016-02-08
TRUE SHORT BREAKOUT! Close (69.69) < Low (69.82)
new date 2016-02-09
TRUE LONG BREAKOUT! Close (69.8443) > High (69.43)
new date 2016-02-10
TRUE SHORT BREAKOUT! Close (72.2701) < Low (72.35)
new date 2016-02-11
TRUE LONG BREAKOUT! Close (69.895) > High (69.81)
new date 2016-02-12
TRUE SHORT BREAKOUT! Close (72.66) < Low (72.85)
new date 2016-02-16
TRUE LONG BREAKOUT! Close (78.53) > High (78.21)
new date 2016-02-17
TRUE SHORT BREAKOUT! Close (80.9975) < Low (81.16)
new date 2016-02-18
TRUE SHORT BREAKOUT! Close (84.1715) < Low (84.28)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (82.06) < Low (84.28)
new date 2016-02-19
closing out position at end of day
TRUE LONG BREAKOUT! Close (82.62) > High (81.66)
new date 2016-02-22
TRUE LONG BREAKOUT! Close (85.7499) > High (85.6)
closing out position at end of day
TRUE LONG BREAKOUT! Close (86.43) > High (85.6)
new date 2016-02-23
TRUE SHORT BREAKOUT! Close (84.81) < Low (85.0)
new date 2016-02-24
TRUE SHORT BREAKOUT! Close (78.83) < Low (79.0)
new date 2016-02-25
TRUE SHORT BREAKOUT! Close (85.17) < Low (85.2844)
new date 2016-02-26
TRUE LONG BREAKOUT! Close (89.3199) > High (89.21)
new date 2016-02-29
TRUE LONG BREAKOUT! Close (87.265) > High (87.2389)
new date 2016-03-01
TRUE SHORT BREAKOUT! Close (86.59) < Low (86.598)
new date 2016-03-02
TRUE SHORT BREAKOUT! Close (92.08) < Low (92.18)
new date 2016-03-03
TRUE SHORT BREAKOUT! Close (91.82) < Low (91.98)
closing out position at end of day
new date 2016-03-04
TRUE SHORT BREAKOUT! Close (91.15) < Low (91.27)
new date 2016-03-07
TRUE LONG BREAKOUT! Close (91.24) > High (91.18)
new date 2016-03-08
TRUE LONG BREAKOUT! Close (89.04) > High (88.92)
new date 2016-03-09
TRUE SHORT BREAKOUT! Close (88.52) < Low (88.58)
new date 2016-03-10
TRUE LONG BREAKOUT! Close (92.04) > High (91.8)
new date 2016-03-11
TRUE LONG BREAKOUT! Close (93.0593) > High (92.98)
new date 2016-03-14
TRUE LONG BREAKOUT! Close (93.825) > High (93.74)
new date 2016-03-15
TRUE SHORT BREAKOUT! Close (93.43) < Low (93.5)
new date 2016-03-16
TRUE LONG BREAKOUT! Close (94.67) > High (94.55)
new date 2016-03-17
TRUE SHORT BREAKOUT! Close (96.03) < Low (96.2445)
new date 2016-03-18
TRUE SHORT BREAKOUT! Close (97.47) < Low (97.5601)
new date 2016-03-21
TRUE LONG BREAKOUT! Close (97.89) > High (97.75)
new date 2016-03-22
TRUE LONG BREAKOUT! Close (97.83) > High (97.67)
new date 2016-03-23
TRUE LONG BREAKOUT! Close (99.2301) > High (99.1796)
new date 2016-03-24
TRUE LONG BREAKOUT! Close (96.14) > High (95.88)
closing out position at end of day
TRUE LONG BREAKOUT! Close (97.35) > High (95.88)
new date 2016-03-28
closing out position at end of day
TRUE SHORT BREAKOUT! Close (96.86) < Low (97.18)
new date 2016-03-29
TRUE LONG BREAKOUT! Close (98.318) > High (96.475)
new date 2016-03-30
TRUE LONG BREAKOUT! Close (103.672) > High (103.48)
new date 2016-03-31
TRUE SHORT BREAKOUT! Close (102.64) < Low (102.6796)
new date 2016-04-01
TRUE LONG BREAKOUT! Close (101.05) > High (100.9199)
new date 2016-04-04
TRUE SHORT BREAKOUT! Close (105.28) < Low (105.3242)
new date 2016-04-05
TRUE SHORT BREAKOUT! Close (102.05) < Low (102.09)
new date 2016-04-06
TRUE LONG BREAKOUT! Close (102.69) > High (102.61)
new date 2016-04-07
TRUE LONG BREAKOUT! Close (105.05) > High (105.03)
new date 2016-04-08
TRUE SHORT BREAKOUT! Close (103.3694) < Low (103.4201)
new date 2016-04-11
TRUE SHORT BREAKOUT! Close (102.6236) < Low (102.66)
new date 2016-04-12
TRUE SHORT BREAKOUT! Close (100.16) < Low (100.19)
new date 2016-04-13
TRUE LONG BREAKOUT! Close (106.01) > High (105.7271)
closing out position at end of day
TRUE LONG BREAKOUT! Close (107.07) > High (105.7271)
new date 2016-04-14
closing out position at end of day
new date 2016-04-15
TRUE SHORT BREAKOUT! Close (106.48) < Low (106.7)
new date 2016-04-18
TRUE LONG BREAKOUT! Close (105.8) > High (105.64)
new date 2016-04-19
TRUE SHORT BREAKOUT! Close (107.1772) < Low (107.56)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (106.1) < Low (107.56)
new date 2016-04-20
closing out position at end of day
TRUE LONG BREAKOUT! Close (106.3) > High (106.2)
new date 2016-04-21
TRUE SHORT BREAKOUT! Close (105.26) < Low (105.73)
new date 2016-04-22
TRUE LONG BREAKOUT! Close (103.2925) > High (103.26)
new date 2016-04-25
TRUE LONG BREAKOUT! Close (101.25) > High (101.08)
new date 2016-04-26
TRUE LONG BREAKOUT! Close (102.1) > High (101.99)
new date 2016-04-27
TRUE LONG BREAKOUT! Close (98.0589) > High (98.0)
new date 2016-04-28
TRUE LONG BREAKOUT! Close (98.1686) > High (98.0)
new date 2016-04-29
TRUE LONG BREAKOUT! Close (94.55) > High (94.3044)
new date 2016-05-02
TRUE LONG BREAKOUT! Close (93.23) > High (93.21)
new date 2016-05-03
TRUE LONG BREAKOUT! Close (93.64) > High (93.55)
new date 2016-05-04
TRUE SHORT BREAKOUT! Close (90.55) < Low (90.75)
new date 2016-05-05
TRUE SHORT BREAKOUT! Close (91.28) < Low (91.31)
new date 2016-05-06
TRUE LONG BREAKOUT! Close (90.43) > High (89.95)
new date 2016-05-09
TRUE LONG BREAKOUT! Close (93.018) > High (92.881)
closing out position at end of day
new date 2016-05-10
TRUE SHORT BREAKOUT! Close (93.498) < Low (93.63)
new date 2016-05-11
TRUE SHORT BREAKOUT! Close (95.7702) < Low (96.0)
new date 2016-05-12
TRUE SHORT BREAKOUT! Close (94.28) < Low (94.44)
new date 2016-05-13
TRUE LONG BREAKOUT! Close (93.3959) > High (93.25)
new date 2016-05-16
TRUE LONG BREAKOUT! Close (92.65) > High (92.52)
new date 2016-05-17
TRUE SHORT BREAKOUT! Close (94.51) < Low (94.8452)
new date 2016-05-18
TRUE LONG BREAKOUT! Close (91.87) > High (91.58)
new date 2016-05-19
TRUE LONG BREAKOUT! Close (91.92) > High (91.84)
new date 2016-05-20
TRUE LONG BREAKOUT! Close (92.9579) > High (92.9)
closing out position at end of day
TRUE LONG BREAKOUT! Close (94.08) > High (92.9)
new date 2016-05-23
closing out position at end of day
TRUE SHORT BREAKOUT! Close (93.56) < Low (94.06)
new date 2016-05-24
TRUE LONG BREAKOUT! Close (95.94) > High (95.86)
new date 2016-05-25
TRUE SHORT BREAKOUT! Close (100.2473) < Low (100.31)
new date 2016-05-26
TRUE SHORT BREAKOUT! Close (101.45) < Low (101.49)
new date 2016-05-27
TRUE LONG BREAKOUT! Close (102.92) > High (102.91)
closing out position at end of day
TRUE LONG BREAKOUT! Close (103.91) > High (102.91)
new date 2016-05-31
closing out position at end of day
TRUE LONG BREAKOUT! Close (104.63) > High (104.46)
new date 2016-06-01
TRUE SHORT BREAKOUT! Close (103.3415) < Low (103.44)
new date 2016-06-02
TRUE SHORT BREAKOUT! Close (103.4) < Low (103.48)
new date 2016-06-03
TRUE SHORT BREAKOUT! Close (103.75) < Low (103.97)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (103.71) < Low (103.97)
new date 2016-06-06
TRUE LONG BREAKOUT! Close (104.99) > High (104.21)
new date 2016-06-07
TRUE LONG BREAKOUT! Close (105.28) > High (105.14)
new date 2016-06-08
TRUE SHORT BREAKOUT! Close (104.4) < Low (104.44)
new date 2016-06-09
TRUE LONG BREAKOUT! Close (103.6) > High (103.51)
new date 2016-06-10
TRUE SHORT BREAKOUT! Close (100.975) < Low (101.0801)
new date 2016-06-13
TRUE LONG BREAKOUT! Close (99.562) > High (99.41)
new date 2016-06-14
TRUE LONG BREAKOUT! Close (98.46) > High (98.36)
new date 2016-06-15
TRUE LONG BREAKOUT! Close (98.76) > High (98.749)
new date 2016-06-16
TRUE SHORT BREAKOUT! Close (95.2) < Low (95.37)
new date 2016-06-17
TRUE SHORT BREAKOUT! Close (95.9044) < Low (95.9701)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (94.5) < Low (95.9701)
new date 2016-06-20
TRUE LONG BREAKOUT! Close (98.32) > High (98.3)
new date 2016-06-21
TRUE LONG BREAKOUT! Close (97.27) > High (97.13)
new date 2016-06-22
TRUE SHORT BREAKOUT! Close (97.11) < Low (97.15)
new date 2016-06-23
TRUE SHORT BREAKOUT! Close (98.15) < Low (98.2)
new date 2016-06-24
TRUE LONG BREAKOUT! Close (91.4685) > High (91.0)
new date 2016-06-27
TRUE SHORT BREAKOUT! Close (85.4799) < Low (85.5625)
new date 2016-06-28
TRUE LONG BREAKOUT! Close (86.06) > High (86.05)
new date 2016-06-29
TRUE LONG BREAKOUT! Close (91.1499) > High (91.0348)
new date 2016-06-30
TRUE SHORT BREAKOUT! Close (93.0645) < Low (93.25)
new date 2016-07-01
TRUE LONG BREAKOUT! Close (97.08) > High (97.0)
closing out position at end of day
TRUE LONG BREAKOUT! Close (97.89) > High (97.0)
new date 2016-07-05
TRUE SHORT BREAKOUT! Close (95.85) < Low (95.95)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (95.91) < Low (95.95)
new date 2016-07-06
TRUE SHORT BREAKOUT! Close (93.82) < Low (93.896)
new date 2016-07-07
TRUE LONG BREAKOUT! Close (99.22) > High (99.14)
new date 2016-07-08
TRUE LONG BREAKOUT! Close (100.9399) > High (100.85)
new date 2016-07-11
TRUE LONG BREAKOUT! Close (105.8521) > High (105.72)
closing out position at end of day
new date 2016-07-12
TRUE LONG BREAKOUT! Close (107.7981) > High (107.73)
new date 2016-07-13
TRUE SHORT BREAKOUT! Close (106.97) < Low (107.0111)
new date 2016-07-14
TRUE SHORT BREAKOUT! Close (108.17) < Low (108.18)
new date 2016-07-15
TRUE SHORT BREAKOUT! Close (108.88) < Low (108.97)
new date 2016-07-18
TRUE LONG BREAKOUT! Close (108.4197) > High (108.4)
new date 2016-07-19
TRUE LONG BREAKOUT! Close (109.92) > High (109.72)
new date 2016-07-20
TRUE LONG BREAKOUT! Close (110.8168) > High (110.75)
new date 2016-07-21
TRUE LONG BREAKOUT! Close (113.15) > High (113.09)
new date 2016-07-22
TRUE SHORT BREAKOUT! Close (111.1702) < Low (111.3531)
new date 2016-07-25
TRUE SHORT BREAKOUT! Close (112.79) < Low (112.795)
new date 2016-07-26
TRUE LONG BREAKOUT! Close (113.59) > High (113.5)
new date 2016-07-27
TRUE SHORT BREAKOUT! Close (115.9752) < Low (116.0399)
new date 2016-07-28
TRUE SHORT BREAKOUT! Close (115.99) < Low (116.25)
new date 2016-07-29
TRUE SHORT BREAKOUT! Close (117.835) < Low (117.94)
new date 2016-08-01
TRUE SHORT BREAKOUT! Close (117.89) < Low (117.94)
new date 2016-08-02
TRUE SHORT BREAKOUT! Close (118.57) < Low (118.58)
new date 2016-08-03
TRUE LONG BREAKOUT! Close (117.1) > High (117.07)
new date 2016-08-04
TRUE LONG BREAKOUT! Close (118.58) > High (118.5389)
new date 2016-08-05
TRUE LONG BREAKOUT! Close (121.658) > High (121.63)
closing out position at end of day
TRUE LONG BREAKOUT! Close (122.53) > High (121.63)
new date 2016-08-08
closing out position at end of day
TRUE SHORT BREAKOUT! Close (122.3) < Low (122.59)
new date 2016-08-09
TRUE LONG BREAKOUT! Close (123.31) > High (123.1979)
closing out position at end of day
TRUE LONG BREAKOUT! Close (123.2) > High (123.1979)
new date 2016-08-10
TRUE SHORT BREAKOUT! Close (122.46) < Low (123.09)
new date 2016-08-11
TRUE LONG BREAKOUT! Close (124.41) > High (124.34)
new date 2016-08-12
TRUE LONG BREAKOUT! Close (123.6) > High (123.569)
closing out position at end of day
TRUE LONG BREAKOUT! Close (124.14) > High (123.569)
new date 2016-08-15
closing out position at end of day
TRUE LONG BREAKOUT! Close (125.5) > High (125.18)
new date 2016-08-16
TRUE SHORT BREAKOUT! Close (123.79) < Low (123.9)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (123.64) < Low (123.9)
new date 2016-08-17
closing out position at end of day
TRUE LONG BREAKOUT! Close (124.2) > High (123.77)
new date 2016-08-18
closing out position at end of day
new date 2016-08-19
TRUE SHORT BREAKOUT! Close (122.89) < Low (123.12)
new date 2016-08-22
TRUE LONG BREAKOUT! Close (123.84) > High (123.64)
closing out position at end of day
TRUE LONG BREAKOUT! Close (124.48) > High (123.64)
new date 2016-08-23
closing out position at end of day
TRUE SHORT BREAKOUT! Close (125.15) < Low (125.73)
new date 2016-08-24
TRUE SHORT BREAKOUT! Close (124.21) < Low (124.65)
new date 2016-08-25
TRUE LONG BREAKOUT! Close (122.0721) > High (121.88)
new date 2016-08-26
TRUE LONG BREAKOUT! Close (123.15) > High (123.06)
new date 2016-08-29
TRUE LONG BREAKOUT! Close (123.21) > High (123.13)
closing out position at end of day
new date 2016-08-30
TRUE SHORT BREAKOUT! Close (122.28) < Low (122.4)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (121.74) < Low (122.4)
new date 2016-08-31
closing out position at end of day
new date 2016-09-01
TRUE LONG BREAKOUT! Close (122.4) > High (122.28)
new date 2016-09-02
TRUE SHORT BREAKOUT! Close (123.68) < Low (124.01)
new date 2016-09-06
TRUE LONG BREAKOUT! Close (124.4064) > High (124.34)
new date 2016-09-07
TRUE LONG BREAKOUT! Close (126.238) > High (126.22)
new date 2016-09-08
TRUE SHORT BREAKOUT! Close (124.25) < Low (124.2928)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (123.87) < Low (124.2928)
new date 2016-09-09
TRUE LONG BREAKOUT! Close (121.3601) > High (121.25)
new date 2016-09-12
TRUE LONG BREAKOUT! Close (114.85) > High (114.62)
new date 2016-09-13
TRUE LONG BREAKOUT! Close (119.3) > High (119.2)
new date 2016-09-14
TRUE LONG BREAKOUT! Close (119.224) > High (119.11)
closing out position at end of day
new date 2016-09-15
TRUE LONG BREAKOUT! Close (120.43) > High (120.4147)
new date 2016-09-16
TRUE SHORT BREAKOUT! Close (123.435) < Low (123.5335)
new date 2016-09-19
TRUE LONG BREAKOUT! Close (125.9411) > High (125.91)
new date 2016-09-20
TRUE LONG BREAKOUT! Close (124.47) > High (124.3551)
new date 2016-09-21
TRUE LONG BREAKOUT! Close (125.228) > High (125.2)
new date 2016-09-22
TRUE LONG BREAKOUT! Close (129.7618) > High (129.73)
closing out position at end of day
TRUE LONG BREAKOUT! Close (130.01) > High (129.73)
new date 2016-09-23
TRUE SHORT BREAKOUT! Close (129.1) < Low (129.249)
new date 2016-09-26
TRUE SHORT BREAKOUT! Close (124.612) < Low (124.8104)
new date 2016-09-27
TRUE LONG BREAKOUT! Close (125.29) > High (125.121)
closing out position at end of day
TRUE LONG BREAKOUT! Close (128.03) > High (125.121)
new date 2016-09-28
closing out position at end of day
TRUE LONG BREAKOUT! Close (128.8) > High (128.62)
new date 2016-09-29
TRUE LONG BREAKOUT! Close (128.5) > High (128.44)
new date 2016-09-30
TRUE SHORT BREAKOUT! Close (126.93) < Low (126.94)
new date 2016-10-03
TRUE SHORT BREAKOUT! Close (127.6) < Low (127.72)
new date 2016-10-04
TRUE LONG BREAKOUT! Close (129.744) > High (129.69)
new date 2016-10-05
TRUE LONG BREAKOUT! Close (129.1133) > High (128.95)
closing out position at end of day
TRUE LONG BREAKOUT! Close (129.0) > High (128.95)
new date 2016-10-06
TRUE SHORT BREAKOUT! Close (127.69) < Low (127.91)
new date 2016-10-07
TRUE SHORT BREAKOUT! Close (128.05) < Low (128.18)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (127.9) < Low (128.18)
new date 2016-10-10
TRUE LONG BREAKOUT! Close (130.3) > High (130.25)
closing out position at end of day
new date 2016-10-11
TRUE SHORT BREAKOUT! Close (128.97) < Low (129.3)
new date 2016-10-12
TRUE SHORT BREAKOUT! Close (123.3604) < Low (123.3826)
new date 2016-10-13
TRUE SHORT BREAKOUT! Close (121.17) < Low (121.35)
new date 2016-10-14
TRUE LONG BREAKOUT! Close (125.5234) > High (125.4725)
new date 2016-10-17
TRUE SHORT BREAKOUT! Close (122.67) < Low (123.11)
new date 2016-10-18
TRUE SHORT BREAKOUT! Close (126.086) < Low (126.2101)
new date 2016-10-19
TRUE LONG BREAKOUT! Close (125.55) > High (125.54)
new date 2016-10-20
TRUE SHORT BREAKOUT! Close (124.48) < Low (124.8)
new date 2016-10-21
TRUE SHORT BREAKOUT! Close (124.3132) < Low (124.41)
new date 2016-10-24
TRUE LONG BREAKOUT! Close (129.82) > High (129.57)
closing out position at end of day
TRUE LONG BREAKOUT! Close (131.11) > High (129.57)
new date 2016-10-25
closing out position at end of day
TRUE SHORT BREAKOUT! Close (129.8) < Low (130.8)
new date 2016-10-26
TRUE SHORT BREAKOUT! Close (126.87) < Low (126.9)
new date 2016-10-27
TRUE SHORT BREAKOUT! Close (128.57) < Low (128.71)
new date 2016-10-28
TRUE LONG BREAKOUT! Close (124.8408) > High (124.34)
new date 2016-10-31
TRUE SHORT BREAKOUT! Close (123.78) < Low (123.913)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (122.78) < Low (123.913)
new date 2016-11-01
TRUE SHORT BREAKOUT! Close (120.758) < Low (122.9)
new date 2016-11-02
TRUE LONG BREAKOUT! Close (119.86) > High (119.79)
new date 2016-11-03
TRUE SHORT BREAKOUT! Close (116.43) < Low (116.45)
new date 2016-11-04
TRUE LONG BREAKOUT! Close (113.67) > High (113.53)
closing out position at end of day
new date 2016-11-07
TRUE LONG BREAKOUT! Close (118.07) > High (118.05)
new date 2016-11-08
TRUE LONG BREAKOUT! Close (120.2) > High (120.13)
new date 2016-11-09
TRUE LONG BREAKOUT! Close (122.74) > High (122.43)
closing out position at end of day
TRUE LONG BREAKOUT! Close (124.62) > High (122.43)
new date 2016-11-10
TRUE SHORT BREAKOUT! Close (117.45) < Low (125.43)
new date 2016-11-11
TRUE LONG BREAKOUT! Close (118.0) > High (117.549)
new date 2016-11-14
TRUE SHORT BREAKOUT! Close (117.09) < Low (117.15)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (114.92) < Low (117.15)
new date 2016-11-15
TRUE LONG BREAKOUT! Close (118.8) > High (117.78)
closing out position at end of day
TRUE LONG BREAKOUT! Close (119.76) > High (117.78)
new date 2016-11-16
TRUE LONG BREAKOUT! Close (121.968) > High (119.0436)
closing out position at end of day
TRUE LONG BREAKOUT! Close (121.64) > High (119.0436)
new date 2016-11-17
closing out position at end of day
TRUE LONG BREAKOUT! Close (124.44) > High (122.34)
new date 2016-11-18
closing out position at end of day
TRUE SHORT BREAKOUT! Close (123.0) < Low (124.67)
new date 2016-11-21
TRUE LONG BREAKOUT! Close (125.66) > High (124.68)
closing out position at end of day
TRUE LONG BREAKOUT! Close (126.83) > High (124.68)
new date 2016-11-22
closing out position at end of day
new date 2016-11-23
TRUE SHORT BREAKOUT! Close (125.8) < Low (126.0)
closing out position at end of day
new date 2016-11-25
TRUE LONG BREAKOUT! Close (127.26) > High (127.2)
new date 2016-11-28
TRUE SHORT BREAKOUT! Close (126.47) < Low (126.8952)
new date 2016-11-29
TRUE LONG BREAKOUT! Close (127.48) > High (127.46)
new date 2016-11-30
TRUE LONG BREAKOUT! Close (128.62) > High (128.56)
new date 2016-12-01
TRUE SHORT BREAKOUT! Close (122.12) < Low (122.132)
new date 2016-12-02
TRUE LONG BREAKOUT! Close (118.25) > High (118.024)
new date 2016-12-05
TRUE SHORT BREAKOUT! Close (118.11) < Low (118.31)
new date 2016-12-06
TRUE SHORT BREAKOUT! Close (119.95) < Low (120.44)
new date 2016-12-07
TRUE LONG BREAKOUT! Close (120.94) > High (120.9)
new date 2016-12-08

/Users/jonathanneo/LearnQuant/.venv/lib/python3.13/site-packages/backtesting/_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '8h'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

Start                     2016-01-04 09:30:00
End                       2023-12-29 16:00:00
Duration                   2916 days 06:30:00
Exposure Time [%]                     46.9989
Equity Final [$]                   76647.8278
Equity Peak [$]                    77993.9757
Commissions [$]                      1180.658
Return [%]                          206.59131
Buy & Hold Return [%]               -52.27206
Return (Ann.) [%]                    15.20938
Volatility (Ann.) [%]                26.25128
CAGR [%]                             10.16521
Sharpe Ratio                          0.57938
Sortino Ratio                          1.2466
Calmar Ratio                          0.49882
Alpha [%]                           206.48693
Beta                                   -0.002
Max. Drawdown [%]                   -30.49082
Avg. Drawdown [%]                    -0.62344
Max. Drawdown Duration      642 days 01:31:00
Avg. Drawdown Duration        3 days 15:41:00
# Trades                                 2322
Win Rate [%]                          37.7261
Best Trade [%]                       11.01554
Worst Trade [%]                      -11.7472
Avg. Trade [%]                          0.031
Max. Trade Duration           3 days 20:29:00
Avg. Trade Duration           0 days 02:52:00
Profit Factor                         1.06948
Expectancy [%]                        0.05067
SQN                                   2.26996
Kelly Criterion                       0.04302
_strategy                 OpeningRangeBrea...
_equity_curve                             ...
_trades                         Size  Entr...
dtype: object

In [7]:
# Aligned to the logic in the research paper as much as possible and included data from 2016 to 2025

import pandas as pd
import datetime as dt
from backtesting import Backtest, Strategy


EARLY_CLOSE_DATES = [
    '2017-07-03 12:59:00',
    '2018-07-03 12:59:00',
    '2018-11-23 12:59:00',
    '2019-12-24 12:59:00',
    '2020-11-27 12:59:00',
    '2020-12-24 12:59:00'
]

# 2. create a strategy class
class OpeningRangeBreakout(Strategy):
    open_range_minutes = 5 # length of the opening range
    last_minute_bar_in_opening_range = dt.time(9, 30 + open_range_minutes)
    exit_minute_bar = dt.time(15, 59)
    risk_percent = 0.01
    take_profit_multiple = 3
    max_leverage = 4

    # what do we want to initialize at the beginning
    def init(self):
        self.current_day        = None   # tracks the current day (YYYY-MM-DD)
        self.current_day_open   = None
        self.opening_range_high = None   # opening range high
        self.opening_range_low  = None   # opening range low
        self.traded_today = False 

    # wait every day is going to have a different opening range high and low
    def _reset_range(self, day, open):
        self.current_day        = day
        self.current_day_open   = open
        self.opening_range_high = None
        self.opening_range_low  = None
        self.traded_today = False


    def _get_position_size(self, entry_price: float, stop_price: float) -> int:
        per_share_risk = abs(entry_price - stop_price)  #  |P − S|  =  R

        if per_share_risk == 0:
            return 0

        # Risk-based cap: position that loses 1 % of equity at the stop
        shares_by_risk = (self.risk_percent * self.equity) / per_share_risk

        # Leverage-based cap: shares affordable with 4× buying power
        shares_by_leverage = (self.max_leverage * self.equity) / entry_price

        # Final size: smaller of the two, floored to an int
        return int(min(shares_by_risk, shares_by_leverage))

    def next(self):
            t = self.data.index[-1]
            current_bar_date = t.date()

            # 1. Handle New Day Reset
            if current_bar_date != self.current_day:
                self._reset_range(current_bar_date, self.data.Open[-1])
                print(f"new date {current_bar_date}")

            # 2. Build the Opening Range (09:30 to 09:35)
            if t.time() <= self.last_minute_bar_in_opening_range:
                if self.opening_range_high is not None:
                    self.opening_range_high = max(self.opening_range_high, self.data.High[-1])
                else:
                    self.opening_range_high = self.data.High[-1]

                if self.opening_range_low is not None:
                    self.opening_range_low = min(self.opening_range_low, self.data.Low[-1])
                else:
                    self.opening_range_low = self.data.Low[-1]

                return  # CRUCIAL: Do not evaluate trades during the opening range window

            # 3. TRUE BREAKOUT MONITORING (09:36 AM onwards)
            if not self.position and not self.traded_today:
                range_size = self.opening_range_high - self.opening_range_low
                current_close = self.data.Close[-1]

                # True Long Breakout Condition: Close crosses ABOVE 5-minute High
                if current_close > self.opening_range_high:
                    stop_loss_price = self.opening_range_low # current_close - (self.take_profit_multiple * range_size)
                    take_profit_price = current_close + (self.take_profit_multiple * range_size)

                    # SAFETY CHECK: Only place order if TP is safely above current price
                    if take_profit_price > current_close:
                        position_size = self._get_position_size(current_close, stop_loss_price)
                        print(f"TRUE LONG BREAKOUT! Close ({current_close}) > High ({self.opening_range_high})")
                        self.buy(size=position_size, tp=take_profit_price, sl=stop_loss_price)
                        self.traded_today = True
                    else:
                        print("Long breakout skipped: Take profit price too close to entry.")

                # True Short Breakout Condition: Close crosses BELOW 5-minute Low
                elif current_close < self.opening_range_low:
                    stop_loss_price = self.opening_range_high
                    take_profit_price = current_close - (self.take_profit_multiple * range_size)

                    # SAFETY CHECK: Only place order if TP is safely BELOW current price
                    if take_profit_price < current_close:
                        position_size = self._get_position_size(current_close, stop_loss_price)
                        print(f"TRUE SHORT BREAKOUT! Close ({current_close}) < Low ({self.opening_range_low})")
                        self.sell(size=position_size, tp=take_profit_price, sl=stop_loss_price)
                        self.traded_today = True
                    else:
                        print("Short breakout skipped: Take profit price too close to entry.")

            # 4. End of Day Closeout
            current_bar_date_time = f"{current_bar_date} {t.time()}"
            if self.position and (t.time() == self.exit_minute_bar or current_bar_date_time in EARLY_CLOSE_DATES):
                print("closing out position at end of day")
                self.position.close()
                self.traded_today = False  # reset for the next day

# 1. read a csv of minute data
df = pd.read_csv("TQQQ_intraday_data.csv", parse_dates=['timestamp'], index_col='timestamp')
df = df.rename(columns={
    'open': 'Open',
    'high': 'High',
    'low': 'Low',
    'close': 'Close',
    'volume': 'Volume'
})
df.index = df.index.tz_convert('America/New_York')
df.index = df.index.tz_localize(None)
df = df.between_time('09:30', '16:00')

def per_share_commission(size, price):
    return abs(size) * 0.0005

# 3. create a backtest, pass in data and the strategy you want to run on the data
bt = Backtest(df, OpeningRangeBreakout, cash=25_000, commission=per_share_commission, margin=0.25)

# run the strategy
stats = bt.run()

# plot ths strategy
bt.plot()

print(stats)

new date 2016-01-04
TRUE LONG BREAKOUT! Close (106.51) > High (106.3599)
new date 2016-01-05
TRUE SHORT BREAKOUT! Close (107.64) < Low (107.77)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (106.5) < Low (107.77)
new date 2016-01-06
TRUE LONG BREAKOUT! Close (101.9772) > High (101.83)
new date 2016-01-07
TRUE LONG BREAKOUT! Close (97.1899) > High (96.86)
new date 2016-01-08
TRUE LONG BREAKOUT! Close (97.145) > High (96.96)
new date 2016-01-11
TRUE SHORT BREAKOUT! Close (92.9) < Low (93.13)
new date 2016-01-12
TRUE LONG BREAKOUT! Close (96.1472) > High (95.8299)
new date 2016-01-13
TRUE LONG BREAKOUT! Close (97.12) > High (96.87)
new date 2016-01-14
TRUE SHORT BREAKOUT! Close (85.71) < Low (85.86)
new date 2016-01-15
TRUE LONG BREAKOUT! Close (83.67) > High (83.64)
new date 2016-01-19
TRUE SHORT BREAKOUT! Close (84.9) < Low (84.91)
new date 2016-01-20
TRUE SHORT BREAKOUT! Close (78.22) < Low (78.73)
new date 2016-01-21
TRUE SHORT BREAKOUT! Close (81.221) < Low (81.27)
new date 2016-01-22
TRUE SHORT BREAKOUT! Close (86.73) < Low (86.9133)
new date 2016-01-25
TRUE SHORT BREAKOUT! Close (88.37) < Low (88.41)
new date 2016-01-26
TRUE SHORT BREAKOUT! Close (85.85) < Low (85.954)
new date 2016-01-27
TRUE SHORT BREAKOUT! Close (86.1211) < Low (86.13)
new date 2016-01-28
TRUE SHORT BREAKOUT! Close (84.56) < Low (84.7)
new date 2016-01-29
TRUE LONG BREAKOUT! Close (85.96) > High (85.5)
new date 2016-02-01
TRUE LONG BREAKOUT! Close (89.2605) > High (88.79)
new date 2016-02-02
TRUE SHORT BREAKOUT! Close (88.74) < Low (88.88)
new date 2016-02-03
TRUE SHORT BREAKOUT! Close (85.5124) < Low (85.5888)
new date 2016-02-04
TRUE SHORT BREAKOUT! Close (82.2047) < Low (82.54)
new date 2016-02-05
TRUE SHORT BREAKOUT! Close (81.2099) < Low (81.21)
new date 2016-02-08
TRUE SHORT BREAKOUT! Close (69.69) < Low (69.82)
new date 2016-02-09
TRUE LONG BREAKOUT! Close (69.8443) > High (69.43)
new date 2016-02-10
TRUE SHORT BREAKOUT! Close (72.2701) < Low (72.35)
new date 2016-02-11
TRUE LONG BREAKOUT! Close (69.895) > High (69.81)
new date 2016-02-12
TRUE SHORT BREAKOUT! Close (72.66) < Low (72.85)
new date 2016-02-16
TRUE LONG BREAKOUT! Close (78.53) > High (78.21)
new date 2016-02-17
TRUE SHORT BREAKOUT! Close (80.9975) < Low (81.16)
new date 2016-02-18
TRUE SHORT BREAKOUT! Close (84.1715) < Low (84.28)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (82.06) < Low (84.28)
new date 2016-02-19
closing out position at end of day
TRUE LONG BREAKOUT! Close (82.62) > High (81.66)
new date 2016-02-22
TRUE LONG BREAKOUT! Close (85.7499) > High (85.6)
closing out position at end of day
TRUE LONG BREAKOUT! Close (86.43) > High (85.6)
new date 2016-02-23
TRUE SHORT BREAKOUT! Close (84.81) < Low (85.0)
new date 2016-02-24
TRUE SHORT BREAKOUT! Close (78.83) < Low (79.0)
new date 2016-02-25
TRUE SHORT BREAKOUT! Close (85.17) < Low (85.2844)
new date 2016-02-26
TRUE LONG BREAKOUT! Close (89.3199) > High (89.21)
new date 2016-02-29
TRUE LONG BREAKOUT! Close (87.265) > High (87.2389)
new date 2016-03-01
TRUE SHORT BREAKOUT! Close (86.59) < Low (86.598)
new date 2016-03-02
TRUE SHORT BREAKOUT! Close (92.08) < Low (92.18)
new date 2016-03-03
TRUE SHORT BREAKOUT! Close (91.82) < Low (91.98)
closing out position at end of day
new date 2016-03-04
TRUE SHORT BREAKOUT! Close (91.15) < Low (91.27)
new date 2016-03-07
TRUE LONG BREAKOUT! Close (91.24) > High (91.18)
new date 2016-03-08
TRUE LONG BREAKOUT! Close (89.04) > High (88.92)
new date 2016-03-09
TRUE SHORT BREAKOUT! Close (88.52) < Low (88.58)
new date 2016-03-10
TRUE LONG BREAKOUT! Close (92.04) > High (91.8)
new date 2016-03-11
TRUE LONG BREAKOUT! Close (93.0593) > High (92.98)
new date 2016-03-14
TRUE LONG BREAKOUT! Close (93.825) > High (93.74)
new date 2016-03-15
TRUE SHORT BREAKOUT! Close (93.43) < Low (93.5)
new date 2016-03-16
TRUE LONG BREAKOUT! Close (94.67) > High (94.55)
new date 2016-03-17
TRUE SHORT BREAKOUT! Close (96.03) < Low (96.2445)
new date 2016-03-18
TRUE SHORT BREAKOUT! Close (97.47) < Low (97.5601)
new date 2016-03-21
TRUE LONG BREAKOUT! Close (97.89) > High (97.75)
new date 2016-03-22
TRUE LONG BREAKOUT! Close (97.83) > High (97.67)
new date 2016-03-23
TRUE LONG BREAKOUT! Close (99.2301) > High (99.1796)
new date 2016-03-24
TRUE LONG BREAKOUT! Close (96.14) > High (95.88)
closing out position at end of day
TRUE LONG BREAKOUT! Close (97.35) > High (95.88)
new date 2016-03-28
closing out position at end of day
TRUE SHORT BREAKOUT! Close (96.86) < Low (97.18)
new date 2016-03-29
TRUE LONG BREAKOUT! Close (98.318) > High (96.475)
new date 2016-03-30
TRUE LONG BREAKOUT! Close (103.672) > High (103.48)
new date 2016-03-31
TRUE SHORT BREAKOUT! Close (102.64) < Low (102.6796)
new date 2016-04-01
TRUE LONG BREAKOUT! Close (101.05) > High (100.9199)
new date 2016-04-04
TRUE SHORT BREAKOUT! Close (105.28) < Low (105.3242)
new date 2016-04-05
TRUE SHORT BREAKOUT! Close (102.05) < Low (102.09)
new date 2016-04-06
TRUE LONG BREAKOUT! Close (102.69) > High (102.61)
new date 2016-04-07
TRUE LONG BREAKOUT! Close (105.05) > High (105.03)
new date 2016-04-08
TRUE SHORT BREAKOUT! Close (103.3694) < Low (103.4201)
new date 2016-04-11
TRUE SHORT BREAKOUT! Close (102.6236) < Low (102.66)
new date 2016-04-12
TRUE SHORT BREAKOUT! Close (100.16) < Low (100.19)
new date 2016-04-13
TRUE LONG BREAKOUT! Close (106.01) > High (105.7271)
closing out position at end of day
TRUE LONG BREAKOUT! Close (107.07) > High (105.7271)
new date 2016-04-14
closing out position at end of day
new date 2016-04-15
TRUE SHORT BREAKOUT! Close (106.48) < Low (106.7)
new date 2016-04-18
TRUE LONG BREAKOUT! Close (105.8) > High (105.64)
new date 2016-04-19
TRUE SHORT BREAKOUT! Close (107.1772) < Low (107.56)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (106.1) < Low (107.56)
new date 2016-04-20
closing out position at end of day
TRUE LONG BREAKOUT! Close (106.3) > High (106.2)
new date 2016-04-21
TRUE SHORT BREAKOUT! Close (105.26) < Low (105.73)
new date 2016-04-22
TRUE LONG BREAKOUT! Close (103.2925) > High (103.26)
new date 2016-04-25
TRUE LONG BREAKOUT! Close (101.25) > High (101.08)
new date 2016-04-26
TRUE LONG BREAKOUT! Close (102.1) > High (101.99)
new date 2016-04-27
TRUE LONG BREAKOUT! Close (98.0589) > High (98.0)
new date 2016-04-28
TRUE LONG BREAKOUT! Close (98.1686) > High (98.0)
new date 2016-04-29
TRUE LONG BREAKOUT! Close (94.55) > High (94.3044)
new date 2016-05-02
TRUE LONG BREAKOUT! Close (93.23) > High (93.21)
new date 2016-05-03
TRUE LONG BREAKOUT! Close (93.64) > High (93.55)
new date 2016-05-04
TRUE SHORT BREAKOUT! Close (90.55) < Low (90.75)
new date 2016-05-05
TRUE SHORT BREAKOUT! Close (91.28) < Low (91.31)
new date 2016-05-06
TRUE LONG BREAKOUT! Close (90.43) > High (89.95)
new date 2016-05-09
TRUE LONG BREAKOUT! Close (93.018) > High (92.881)
closing out position at end of day
new date 2016-05-10
TRUE SHORT BREAKOUT! Close (93.498) < Low (93.63)
new date 2016-05-11
TRUE SHORT BREAKOUT! Close (95.7702) < Low (96.0)
new date 2016-05-12
TRUE SHORT BREAKOUT! Close (94.28) < Low (94.44)
new date 2016-05-13
TRUE LONG BREAKOUT! Close (93.3959) > High (93.25)
new date 2016-05-16
TRUE LONG BREAKOUT! Close (92.65) > High (92.52)
new date 2016-05-17
TRUE SHORT BREAKOUT! Close (94.51) < Low (94.8452)
new date 2016-05-18
TRUE LONG BREAKOUT! Close (91.87) > High (91.58)
new date 2016-05-19
TRUE LONG BREAKOUT! Close (91.92) > High (91.84)
new date 2016-05-20
TRUE LONG BREAKOUT! Close (92.9579) > High (92.9)
closing out position at end of day
TRUE LONG BREAKOUT! Close (94.08) > High (92.9)
new date 2016-05-23
closing out position at end of day
TRUE SHORT BREAKOUT! Close (93.56) < Low (94.06)
new date 2016-05-24
TRUE LONG BREAKOUT! Close (95.94) > High (95.86)
new date 2016-05-25
TRUE SHORT BREAKOUT! Close (100.2473) < Low (100.31)
new date 2016-05-26
TRUE SHORT BREAKOUT! Close (101.45) < Low (101.49)
new date 2016-05-27
TRUE LONG BREAKOUT! Close (102.92) > High (102.91)
closing out position at end of day
TRUE LONG BREAKOUT! Close (103.91) > High (102.91)
new date 2016-05-31
closing out position at end of day
TRUE LONG BREAKOUT! Close (104.63) > High (104.46)
new date 2016-06-01
TRUE SHORT BREAKOUT! Close (103.3415) < Low (103.44)
new date 2016-06-02
TRUE SHORT BREAKOUT! Close (103.4) < Low (103.48)
new date 2016-06-03
TRUE SHORT BREAKOUT! Close (103.75) < Low (103.97)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (103.71) < Low (103.97)
new date 2016-06-06
TRUE LONG BREAKOUT! Close (104.99) > High (104.21)
new date 2016-06-07
TRUE LONG BREAKOUT! Close (105.28) > High (105.14)
new date 2016-06-08
TRUE SHORT BREAKOUT! Close (104.4) < Low (104.44)
new date 2016-06-09
TRUE LONG BREAKOUT! Close (103.6) > High (103.51)
new date 2016-06-10
TRUE SHORT BREAKOUT! Close (100.975) < Low (101.0801)
new date 2016-06-13
TRUE LONG BREAKOUT! Close (99.562) > High (99.41)
new date 2016-06-14
TRUE LONG BREAKOUT! Close (98.46) > High (98.36)
new date 2016-06-15
TRUE LONG BREAKOUT! Close (98.76) > High (98.749)
new date 2016-06-16
TRUE SHORT BREAKOUT! Close (95.2) < Low (95.37)
new date 2016-06-17
TRUE SHORT BREAKOUT! Close (95.9044) < Low (95.9701)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (94.5) < Low (95.9701)
new date 2016-06-20
TRUE LONG BREAKOUT! Close (98.32) > High (98.3)
new date 2016-06-21
TRUE LONG BREAKOUT! Close (97.27) > High (97.13)
new date 2016-06-22
TRUE SHORT BREAKOUT! Close (97.11) < Low (97.15)
new date 2016-06-23
TRUE SHORT BREAKOUT! Close (98.15) < Low (98.2)
new date 2016-06-24
TRUE LONG BREAKOUT! Close (91.4685) > High (91.0)
new date 2016-06-27
TRUE SHORT BREAKOUT! Close (85.4799) < Low (85.5625)
new date 2016-06-28
TRUE LONG BREAKOUT! Close (86.06) > High (86.05)
new date 2016-06-29
TRUE LONG BREAKOUT! Close (91.1499) > High (91.0348)
new date 2016-06-30
TRUE SHORT BREAKOUT! Close (93.0645) < Low (93.25)
new date 2016-07-01
TRUE LONG BREAKOUT! Close (97.08) > High (97.0)
closing out position at end of day
TRUE LONG BREAKOUT! Close (97.89) > High (97.0)
new date 2016-07-05
TRUE SHORT BREAKOUT! Close (95.85) < Low (95.95)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (95.91) < Low (95.95)
new date 2016-07-06
TRUE SHORT BREAKOUT! Close (93.82) < Low (93.896)
new date 2016-07-07
TRUE LONG BREAKOUT! Close (99.22) > High (99.14)
new date 2016-07-08
TRUE LONG BREAKOUT! Close (100.9399) > High (100.85)
new date 2016-07-11
TRUE LONG BREAKOUT! Close (105.8521) > High (105.72)
closing out position at end of day
new date 2016-07-12
TRUE LONG BREAKOUT! Close (107.7981) > High (107.73)
new date 2016-07-13
TRUE SHORT BREAKOUT! Close (106.97) < Low (107.0111)
new date 2016-07-14
TRUE SHORT BREAKOUT! Close (108.17) < Low (108.18)
new date 2016-07-15
TRUE SHORT BREAKOUT! Close (108.88) < Low (108.97)
new date 2016-07-18
TRUE LONG BREAKOUT! Close (108.4197) > High (108.4)
new date 2016-07-19
TRUE LONG BREAKOUT! Close (109.92) > High (109.72)
new date 2016-07-20
TRUE LONG BREAKOUT! Close (110.8168) > High (110.75)
new date 2016-07-21
TRUE LONG BREAKOUT! Close (113.15) > High (113.09)
new date 2016-07-22
TRUE SHORT BREAKOUT! Close (111.1702) < Low (111.3531)
new date 2016-07-25
TRUE SHORT BREAKOUT! Close (112.79) < Low (112.795)
new date 2016-07-26
TRUE LONG BREAKOUT! Close (113.59) > High (113.5)
new date 2016-07-27
TRUE SHORT BREAKOUT! Close (115.9752) < Low (116.0399)
new date 2016-07-28
TRUE SHORT BREAKOUT! Close (115.99) < Low (116.25)
new date 2016-07-29
TRUE SHORT BREAKOUT! Close (117.835) < Low (117.94)
new date 2016-08-01
TRUE SHORT BREAKOUT! Close (117.89) < Low (117.94)
new date 2016-08-02
TRUE SHORT BREAKOUT! Close (118.57) < Low (118.58)
new date 2016-08-03
TRUE LONG BREAKOUT! Close (117.1) > High (117.07)
new date 2016-08-04
TRUE LONG BREAKOUT! Close (118.58) > High (118.5389)
new date 2016-08-05
TRUE LONG BREAKOUT! Close (121.658) > High (121.63)
closing out position at end of day
TRUE LONG BREAKOUT! Close (122.53) > High (121.63)
new date 2016-08-08
closing out position at end of day
TRUE SHORT BREAKOUT! Close (122.3) < Low (122.59)
new date 2016-08-09
TRUE LONG BREAKOUT! Close (123.31) > High (123.1979)
closing out position at end of day
TRUE LONG BREAKOUT! Close (123.2) > High (123.1979)
new date 2016-08-10
TRUE SHORT BREAKOUT! Close (122.46) < Low (123.09)
new date 2016-08-11
TRUE LONG BREAKOUT! Close (124.41) > High (124.34)
new date 2016-08-12
TRUE LONG BREAKOUT! Close (123.6) > High (123.569)
closing out position at end of day
TRUE LONG BREAKOUT! Close (124.14) > High (123.569)
new date 2016-08-15
closing out position at end of day
TRUE LONG BREAKOUT! Close (125.5) > High (125.18)
new date 2016-08-16
TRUE SHORT BREAKOUT! Close (123.79) < Low (123.9)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (123.64) < Low (123.9)
new date 2016-08-17
closing out position at end of day
TRUE LONG BREAKOUT! Close (124.2) > High (123.77)
new date 2016-08-18
closing out position at end of day
new date 2016-08-19
TRUE SHORT BREAKOUT! Close (122.89) < Low (123.12)
new date 2016-08-22
TRUE LONG BREAKOUT! Close (123.84) > High (123.64)
closing out position at end of day
TRUE LONG BREAKOUT! Close (124.48) > High (123.64)
new date 2016-08-23
closing out position at end of day
TRUE SHORT BREAKOUT! Close (125.15) < Low (125.73)
new date 2016-08-24
TRUE SHORT BREAKOUT! Close (124.21) < Low (124.65)
new date 2016-08-25
TRUE LONG BREAKOUT! Close (122.0721) > High (121.88)
new date 2016-08-26
TRUE LONG BREAKOUT! Close (123.15) > High (123.06)
new date 2016-08-29
TRUE LONG BREAKOUT! Close (123.21) > High (123.13)
closing out position at end of day
new date 2016-08-30
TRUE SHORT BREAKOUT! Close (122.28) < Low (122.4)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (121.74) < Low (122.4)
new date 2016-08-31
closing out position at end of day
new date 2016-09-01
TRUE LONG BREAKOUT! Close (122.4) > High (122.28)
new date 2016-09-02
TRUE SHORT BREAKOUT! Close (123.68) < Low (124.01)
new date 2016-09-06
TRUE LONG BREAKOUT! Close (124.4064) > High (124.34)
new date 2016-09-07
TRUE LONG BREAKOUT! Close (126.238) > High (126.22)
new date 2016-09-08
TRUE SHORT BREAKOUT! Close (124.25) < Low (124.2928)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (123.87) < Low (124.2928)
new date 2016-09-09
TRUE LONG BREAKOUT! Close (121.3601) > High (121.25)
new date 2016-09-12
TRUE LONG BREAKOUT! Close (114.85) > High (114.62)
new date 2016-09-13
TRUE LONG BREAKOUT! Close (119.3) > High (119.2)
new date 2016-09-14
TRUE LONG BREAKOUT! Close (119.224) > High (119.11)
closing out position at end of day
new date 2016-09-15
TRUE LONG BREAKOUT! Close (120.43) > High (120.4147)
new date 2016-09-16
TRUE SHORT BREAKOUT! Close (123.435) < Low (123.5335)
new date 2016-09-19
TRUE LONG BREAKOUT! Close (125.9411) > High (125.91)
new date 2016-09-20
TRUE LONG BREAKOUT! Close (124.47) > High (124.3551)
new date 2016-09-21
TRUE LONG BREAKOUT! Close (125.228) > High (125.2)
new date 2016-09-22
TRUE LONG BREAKOUT! Close (129.7618) > High (129.73)
closing out position at end of day
TRUE LONG BREAKOUT! Close (130.01) > High (129.73)
new date 2016-09-23
TRUE SHORT BREAKOUT! Close (129.1) < Low (129.249)
new date 2016-09-26
TRUE SHORT BREAKOUT! Close (124.612) < Low (124.8104)
new date 2016-09-27
TRUE LONG BREAKOUT! Close (125.29) > High (125.121)
closing out position at end of day
TRUE LONG BREAKOUT! Close (128.03) > High (125.121)
new date 2016-09-28
closing out position at end of day
TRUE LONG BREAKOUT! Close (128.8) > High (128.62)
new date 2016-09-29
TRUE LONG BREAKOUT! Close (128.5) > High (128.44)
new date 2016-09-30
TRUE SHORT BREAKOUT! Close (126.93) < Low (126.94)
new date 2016-10-03
TRUE SHORT BREAKOUT! Close (127.6) < Low (127.72)
new date 2016-10-04
TRUE LONG BREAKOUT! Close (129.744) > High (129.69)
new date 2016-10-05
TRUE LONG BREAKOUT! Close (129.1133) > High (128.95)
closing out position at end of day
TRUE LONG BREAKOUT! Close (129.0) > High (128.95)
new date 2016-10-06
TRUE SHORT BREAKOUT! Close (127.69) < Low (127.91)
new date 2016-10-07
TRUE SHORT BREAKOUT! Close (128.05) < Low (128.18)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (127.9) < Low (128.18)
new date 2016-10-10
TRUE LONG BREAKOUT! Close (130.3) > High (130.25)
closing out position at end of day
new date 2016-10-11
TRUE SHORT BREAKOUT! Close (128.97) < Low (129.3)
new date 2016-10-12
TRUE SHORT BREAKOUT! Close (123.3604) < Low (123.3826)
new date 2016-10-13
TRUE SHORT BREAKOUT! Close (121.17) < Low (121.35)
new date 2016-10-14
TRUE LONG BREAKOUT! Close (125.5234) > High (125.4725)
new date 2016-10-17
TRUE SHORT BREAKOUT! Close (122.67) < Low (123.11)
new date 2016-10-18
TRUE SHORT BREAKOUT! Close (126.086) < Low (126.2101)
new date 2016-10-19
TRUE LONG BREAKOUT! Close (125.55) > High (125.54)
new date 2016-10-20
TRUE SHORT BREAKOUT! Close (124.48) < Low (124.8)
new date 2016-10-21
TRUE SHORT BREAKOUT! Close (124.3132) < Low (124.41)
new date 2016-10-24
TRUE LONG BREAKOUT! Close (129.82) > High (129.57)
closing out position at end of day
TRUE LONG BREAKOUT! Close (131.11) > High (129.57)
new date 2016-10-25
closing out position at end of day
TRUE SHORT BREAKOUT! Close (129.8) < Low (130.8)
new date 2016-10-26
TRUE SHORT BREAKOUT! Close (126.87) < Low (126.9)
new date 2016-10-27
TRUE SHORT BREAKOUT! Close (128.57) < Low (128.71)
new date 2016-10-28
TRUE LONG BREAKOUT! Close (124.8408) > High (124.34)
new date 2016-10-31
TRUE SHORT BREAKOUT! Close (123.78) < Low (123.913)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (122.78) < Low (123.913)
new date 2016-11-01
TRUE SHORT BREAKOUT! Close (120.758) < Low (122.9)
new date 2016-11-02
TRUE LONG BREAKOUT! Close (119.86) > High (119.79)
new date 2016-11-03
TRUE SHORT BREAKOUT! Close (116.43) < Low (116.45)
new date 2016-11-04
TRUE LONG BREAKOUT! Close (113.67) > High (113.53)
closing out position at end of day
new date 2016-11-07
TRUE LONG BREAKOUT! Close (118.07) > High (118.05)
new date 2016-11-08
TRUE LONG BREAKOUT! Close (120.2) > High (120.13)
new date 2016-11-09
TRUE LONG BREAKOUT! Close (122.74) > High (122.43)
closing out position at end of day
TRUE LONG BREAKOUT! Close (124.62) > High (122.43)
new date 2016-11-10
TRUE SHORT BREAKOUT! Close (117.45) < Low (125.43)
new date 2016-11-11
TRUE LONG BREAKOUT! Close (118.0) > High (117.549)
new date 2016-11-14
TRUE SHORT BREAKOUT! Close (117.09) < Low (117.15)
closing out position at end of day
TRUE SHORT BREAKOUT! Close (114.92) < Low (117.15)
new date 2016-11-15
TRUE LONG BREAKOUT! Close (118.8) > High (117.78)
closing out position at end of day
TRUE LONG BREAKOUT! Close (119.76) > High (117.78)
new date 2016-11-16
TRUE LONG BREAKOUT! Close (121.968) > High (119.0436)
closing out position at end of day
TRUE LONG BREAKOUT! Close (121.64) > High (119.0436)
new date 2016-11-17
closing out position at end of day
TRUE LONG BREAKOUT! Close (124.44) > High (122.34)
new date 2016-11-18
closing out position at end of day
TRUE SHORT BREAKOUT! Close (123.0) < Low (124.67)
new date 2016-11-21
TRUE LONG BREAKOUT! Close (125.66) > High (124.68)
closing out position at end of day
TRUE LONG BREAKOUT! Close (126.83) > High (124.68)
new date 2016-11-22
closing out position at end of day
new date 2016-11-23
TRUE SHORT BREAKOUT! Close (125.8) < Low (126.0)
closing out position at end of day
new date 2016-11-25
TRUE LONG BREAKOUT! Close (127.26) > High (127.2)
new date 2016-11-28
TRUE SHORT BREAKOUT! Close (126.47) < Low (126.8952)
new date 2016-11-29
TRUE LONG BREAKOUT! Close (127.48) > High (127.46)
new date 2016-11-30
TRUE LONG BREAKOUT! Close (128.62) > High (128.56)
new date 2016-12-01
TRUE SHORT BREAKOUT! Close (122.12) < Low (122.132)
new date 2016-12-02
TRUE LONG BREAKOUT! Close (118.25) > High (118.024)
new date 2016-12-05
TRUE SHORT BREAKOUT! Close (118.11) < Low (118.31)
new date 2016-12-06
TRUE SHORT BREAKOUT! Close (119.95) < Low (120.44)
new date 2016-12-07
TRUE LONG BREAKOUT! Close (120.94) > High (120.9)
new date 2016-12-08

/Users/jonathanneo/LearnQuant/.venv/lib/python3.13/site-packages/backtesting/_plotting.py:141: UserWarning: Data contains too many candlesticks to plot; downsampling to '1D'. See `Backtest.plot(resample=...)`
  warnings.warn(f"Data contains too many candlesticks to plot; downsampling to {freq!r}. "

Start                     2016-01-04 09:30:00
End                       2025-12-30 16:00:00
Duration                   3648 days 06:30:00
Exposure Time [%]                    46.86024
Equity Final [$]                  152760.9227
Equity Peak [$]                   180009.6865
Commissions [$]                      2027.297
Return [%]                          511.04369
Buy & Hold Return [%]                -48.9621
Return (Ann.) [%]                    20.02289
Volatility (Ann.) [%]                27.51059
CAGR [%]                             13.31751
Sharpe Ratio                          0.72782
Sortino Ratio                         1.65389
Calmar Ratio                          0.65669
Alpha [%]                           510.89838
Beta                                 -0.00297
Max. Drawdown [%]                   -30.49082
Avg. Drawdown [%]                    -0.67382
Max. Drawdown Duration      642 days 01:31:00
Avg. Drawdown Duration        3 days 01:55:00
# Trades                                 2897
Win Rate [%]                         38.10839
Best Trade [%]                       11.01554
Worst Trade [%]                      -11.7472
Avg. Trade [%]                        0.04537
Max. Trade Duration           3 days 20:29:00
Avg. Trade Duration           0 days 02:50:00
Profit Factor                         1.09067
Expectancy [%]                        0.06404
SQN                                   2.90814
Kelly Criterion                       0.05681
_strategy                 OpeningRangeBrea...
_equity_curve                             ...
_trades                         Size  Entr...
dtype: object

In [6]:
# 1. Isolate a single trading day where you know a trade happened
df_single_day = df.loc['2024-12-20':'2024-12-20']

# 2. Run a clean micro-backtest for just that day
bt_day = Backtest(df_single_day, OpeningRangeBreakout, cash=25_000, commission=per_share_commission, margin=0.25)
stats_day = bt_day.run()

# 3. Force it to render uncompressed 1-minute data in a full browser tab
bt_day.plot(resample=False, open_browser=True)

# Extract the complete history of closed trades
trade_log = stats['_trades']

# Filter the ledger to only show trades that occurred on your day of interest
specific_day_trades = trade_log[trade_log['EntryTime'].dt.date == pd.to_datetime('2024-12-20').date()]

specific_day_trades

new date 2024-12-20
TRUE LONG BREAKOUT! Close (79.5499) > High (79.2)

,Size,EntryBar,ExitBar,EntryPrice,ExitPrice,SL,TP,PnL,Commission,ReturnPct,EntryTime,ExitTime,Duration,Tag
2596,1461,875018,875029,79.5498,78.75,78.75,80.9599,-1169.9688,1.461,-0.010067,2024-12-20 09:39:00,2024-12-20 09:50:00,0 days 00:11:00,None